### ISSUE TITLE
Missing environment images for planet overview and comm screen

### ISSUE THREAD

**Issue by dosaki** [dosaki/strange-homeworlds#1]
Can't figure it out :(

The problem is depicted in this thread https://forum.paradoxplaza.com/forum/index.php?threads/help-setting-planet-type-mage.955238/

**Comment by dosaki** [comment]
Experiment with 

```
show_city = no
```

Maybe there's a parameter in `planet_classes`

**Comment by E-Ledere** [comment]
I've found a fix for this issue.

Inside of 00_planet_classes.txt you need to add the following line to each colonize able planet type:

picture = pc_tundra

pc_tundra can be replaced with any other standard habitable planet, ie pc_desert, pc_arctic, etc.

As an example, this is how I set up pc_barren_cold

```
pc_barren_cold ={
    entity = "cold_barren_planet"
    entity_scale = @planet_standard_scale
    picture = pc_arctic
    icon_frame = 9

    climate = "inhospitable"

    atmosphere_color        = hsv { 0.55 0.3 0.75 }     #DONE
    atmosphere_intensity    = 1.0
    atmosphere_width        = 0.5

    min_distance_from_sun = 40
    max_distance_from_sun = 200
    spawn_odds = 10

    extra_orbit_size = 0
    extra_planet_count = 0

    chance_of_ring = 0.2

    planet_size = { min = 12 max = 30 }
    moon_size = { min = 6 max = 10 }

    colonizable = yes
    starting_planet = no
}
```

The only issue is that this fix will have to be applied to Colonize Unlimited as it requires modification of the 00_planet_classes.txt. However, I felt that it was apt to reply here as the bug is located here.

I hope this helps!

**Comment by dosaki** [comment]
You're awesome.

**Comment by dosaki** [comment]
I fixed this on [Colonize Unlimited](https://github.com/Thomahawk2k/Colonize-Unlimited)
